feat: Nuevo cheatsheet para next.js
nachovigilante/cheatsheets pull request #13
Opened 2023-03-03 21:09 UTC by dan-dervich

Si ves alguna cosa que cambiarias o sacarias avisame porfavor asi puedo aprender para las proximas veces.

2023-03-03 21:10 UTC, dan-dervich commented
feat: Nuevo cheatsheet para next.js

2023-03-06 13:06 UTC, nachovigilante commented
Muy buen aporte! Está muy bien explicado y tiene un montón de cosas que me parecen importantes. Tengo un par de cositas para mejorar:

- Hay muchos errores de ortografía (faltan todas las tildes por ejemplo). Te sugiero pasarlo por algún corrector.
- Si bien está muy bien explicado, me gustaría que tuviera un lenguaje más formal y menos coloquial (también te sirve para practicar la escritura de documentación o descripción técnica).
- Ojo con usar `h1`, de estos tiene que haber uno solo (el que dice "NEXT.JS V12"). Todos los demás deberían ser `h2` y obvio que las subsecciones deberían decrecer junto con estos.
- Evita usar las mayúsculas como en el primer subtítulo, así hay consistencia entre los distintos subtítulos
- Donde dice "docs originales" yo lo cambiaría por "Ver más" para que sea igual a los cheatsheets que ya están.

2023-03-06 13:08 UTC, dan-dervich commented
> Muy buen aporte! Está muy bien explicado y tiene un montón de cosas que me parecen importantes. Tengo un par de cositas para mejorar:
> 
> * Hay muchos errores de ortografía (faltan todas las tildes por ejemplo). Te sugiero pasarlo por algún corrector.
> * Si bien está muy bien explicado, me gustaría que tuviera un lenguaje más formal y menos coloquial (también te sirve para practicar la escritura de documentación o descripción técnica).
> * Ojo con usar `h1`, de estos tiene que haber uno solo (el que dice "NEXT.JS V12"). Todos los demás deberían ser `h2` y obvio que las subsecciones deberían decrecer junto con estos.
> * Evita usar las mayúsculas como en el primer subtítulo, así hay consistencia entre los distintos subtítulos
> * Donde dice "docs originales" yo lo cambiaría por "Ver más" para que sea igual a los cheatsheets que ya están.

Ok, hoy a la noche los soluciono y te mando otro PR.

2023-03-06 13:10 UTC, nachovigilante requested changes
Muy buen aporte! Está muy bien explicado y tiene un montón de cosas que me parecen importantes. Tengo un par de cositas para mejorar:

Hay muchos errores de ortografía (faltan todas las tildes por ejemplo). Te sugiero pasarlo por algún corrector.
Si bien está muy bien explicado, me gustaría que tuviera un lenguaje más formal y menos coloquial (también te sirve para practicar la escritura de documentación o descripción técnica).
Ojo con usar h1, de estos tiene que haber uno solo (el que dice "NEXT.JS V12"). Todos los demás deberían ser h2 y obvio que las subsecciones deberían decrecer junto con estos.
Evita usar las mayúsculas como en el primer subtítulo, así hay consistencia entre los distintos subtítulos
Donde dice "docs originales" yo lo cambiaría por "Ver más" para que sea igual a los cheatsheets que ya están.

2023-03-11 16:28 UTC, nachovigilante approved these changes
Buenísimo, muy buen aporte!

2023-03-11 16:29 UTC, merged