feat(content): Added content of slicing to python cheatsheet
nachovigilante/cheatsheets pull request #2
Opened 2022-08-23 00:23 UTC by LucaFedericoMarty

Agregue contenido a la cheatsheet de Python sobre el mecanismo de slicing en el caso de listas

Source:

[https://stackoverflow.com/questions/509211/understanding-slicing](url)

[https://www.w3schools.com/python/python_strings_slicing.asp](url)

2022-08-23 21:48 UTC, JZylber commented
¡Muy buena contribución! Lo que sí, como con slicing lo que hacés es crear sublistas, no se si lo pondría bajo esa subsección, que está más referido a acceder y asignar **elementos** de una lista (tal vez habría que mejorar ese título también). Me armaría otro título que sea "Sublistas" (misma jerarquía que acceso y asignación) y puede ir al final de la sección de listas.

2022-08-23 21:56 UTC, JZylber requested changes
Y ya que estoy, molesto un poco con algunos typos. "índice" y sus variaciones en plural llevan tilde, "métodos" está mal escrito. También llevan tilde "rápidamente", "posición", y "último" (y sus variaciones).  ¡La explicación está genial! Pero ya que estamos hago un poquito de editor pesado.

2022-08-24 22:57 UTC, nachovigilante commented on cheatsheets/python.md
> +Podemos acceder a varios elementos de una lista rapidamente utilizando sus posiciones o indices. Este metedo se llama `slicing` y se basa en la siguente estructura `lista[comienzo:final:instancias]`.
> ... se llama `slicing` y ...

En esta parte, "slicing" debería ir sin backticks ya que no es código, podés ponerlo de esta manera _slicing_ o **slicing**

> ... `lista[comienzo:final:instancias]` ...

Acá sí están bien utilizados los backticks, pero el término "instancias" es ambiguo. Yo usaría "step" o "paso".

2022-08-24 22:57 UTC, nachovigilante commented on cheatsheets/python.md
>  Puedo no solo acceder, sino también modificar elementos en una lista. Para eso uso operadores de asignación como =, o de modificación como += sobre el elemento deseado:
> ... como =, o de modificación como += sobre ...

El "=" y el "+=" deberían llevar backticks porque son código.

2022-08-24 22:58 UTC, nachovigilante requested changes
Te sugiero estos cambios

2022-08-26 22:44 UTC, LucaFedericoMarty commented
Ahí hice todos los cambios que me pidieron y agregue lo de los strings, ya que me parecía importante mencionar su posibilidad.

2022-08-27 02:44 UTC, JZylber requested changes
¡Buenísimos los cambios! Pero tengo unas cosas para que comentar de lo que agregaste de strings. _Uy, que pesados, más correcciones._
### El problema
**Los strings no son listas en Python**. Tienen algunos comportamientos parecidos, pero son diferentes en formas bastante fundamentales. Menciono algunas de las más importantes:
- Los strings son inmutables (no cambian después de su creación), las listas no. Esto tiene como consecuencia por ejemplo que las listas tienen longitud variable mientras que los strings no. Otra consecuencia es que puedo cambiar elementos de una lista, mientras que no puedo hacerlo en un string. **Los strings no soportan la operación de asignación.**
- Hay métodos que tienen las listas que no tienen los strings y viceversa. Así como los strings no tienen ni pop ni append, las listas no tienen format por ejemplo. Comparten algunos métodos, pero muchos otros no.
- **Las listas se pasan por referencia mientras los strings por copia**. Le tendría que dedicar una subsección entera en funciones explicando esto (y lo voy a hacer eventualmente), pero esto cambia completamente como se comportan frente a funciones. 

Fuente: https://developers.google.com/edu/python/strings
### Posibles soluciones
_¿Bueno y cómo lo arreglamos?_ Sugiero 2 posibles formas, pero estoy abierto a otras ideas

1. Mandar el slicing de strings a un lugar exclusivo para strings, compartiendo lugar con otras estucturas de datos. La jerarquía de títulos iría _Estructuras Básicas -> Strings -> Substrings_. Si, strings quedaría súper pelado, pero un lugar para hablar de strings en python es súper necesario. Nos estaríamos adelantando a futuros agregados del tema. 
2. Mandar slicing entero a su propia sección, fuera de listas y estructuras de básicas. Irían tanto el slicing de listas como el de strings. 

Obviamente habría que también cambiar la parte en que afirmás que los strings son y funcionan como listas. _¡Qué pesado Julián!_ Sólo molesto para que el cheatsheet sea lo más claro posible.
Escribiendo estas sugerencias me inclino más por la 1, pero acepto otras ideas. Desde ya, infinitas gracias por colaborar con estos apuntes.

2022-08-29 20:37 UTC, merged